name: Build Dino Client

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: temurin

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 7.6  # Latest Gradle version compatible with Java 8

    - name: Build mod with Gradle
      run: gradle build

    - name: Upload jar
      uses: actions/upload-artifact@v4
      with:
        name: Dino-Jar
        path: build/libs/*.jar
